"""init

Revision ID: de6b38f9aed7
Revises: 
Create Date: 2021-12-10 22:40:38.926890

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "de6b38f9aed7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic_model",
        sa.Column("model_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id", "version", name="_model_id_version_uc"),
    )
    op.create_table(
        "topic",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("topic_index", sa.Integer(), nullable=False),
        sa.Column("some_field", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_model_id"],
            ["topic_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word")
    op.drop_table("topic")
    op.drop_table("topic_model")
    # ### end Alembic commands ###
